Task 5
js-tasks-ru/nodejs-20210513_nataliya-karpenko pull request #4
Opened 2021-05-30 12:37 UTC by Netaly79

2021-05-30 12:38 UTC, jsru commented
Добавляю преподавателя (@RidgeA) для код-ревью.

2021-05-30 13:06 UTC, RidgeA requested changes

2021-05-30 13:06 UTC, RidgeA commented on 05-http-server-streams/01-file-server-get/server.js
> +      str.on('readable', (error, data) => {
Использован е метода `pipe` предпочтительнее если этого позволяет ситуация. В данном случае вполне можно воспользоваться этим методом. Переделайте, пожалуйста, задачу используя метод `pipe`.

2021-05-30 16:22 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-05-30 17:14 UTC, jsru commented
Добавляю преподавателя (@RidgeA) для код-ревью.

2021-05-30 17:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @RidgeA

2021-05-31 08:07 UTC, RidgeA requested changes

2021-05-31 08:07 UTC, RidgeA commented on 05-http-server-streams/01-file-server-get/server.js
> +          req.pipe(rst, {end: false}).pipe(res);
в данном случае `req` тут в цепочке вообще не нужен, достаточно передать из `rst` в `res`

2021-05-31 08:07 UTC, RidgeA commented on 05-http-server-streams/01-file-server-get/server.js
> +        if (!fs.existsSync(filepath)) {
При использовании синхронных функций в обработчиках http запросов надо помнить о том, что синхронные функции блокируют event loop и другие запросы(который будут приходить на сервер) обрабатываться не будут

2021-05-31 16:20 UTC, jsru commented
Добавляю преподавателя (@RidgeA) для код-ревью.

2021-05-31 16:20 UTC, Netaly79 commented on 05-http-server-streams/01-file-server-get/server.js
> +          req.pipe(rst, {end: false}).pipe(res);
changed, thanks

2021-05-31 16:21 UTC, Netaly79 commented on 05-http-server-streams/01-file-server-get/server.js
> +        if (!fs.existsSync(filepath)) {
Синхронная функция удалена

2021-06-01 08:07 UTC, RidgeA approved these changes

2021-06-01 08:07 UTC, RidgeA commented on 05-http-server-streams/01-file-server-get/server.js
> +        req.on('aborted', () => {
Я не помню, было ли это изначально (возможно пропустил), но этот код удалит файл который запросил клиент, если соединение прервется. Это очень неожиданное поведение.

2021-06-01 08:08 UTC, merged

2021-06-01 09:10 UTC, Netaly79 commented on 05-http-server-streams/01-file-server-get/server.js
> +        req.on('aborted', () => {
Жертва копи-паста из второй задачи. Спасибо за замечание